// Mock data — replaces Supabase calls so the UI works without a database connection.

export const MOCK_APPLICATIONS = [
  {
    id: 'app-1',
    company: 'Goldman Sachs',
    role: 'Summer Analyst – Investment Banking',
    status: 'Applied',
    deadline: '2026-06-01',
    location: 'London',
    salary: '£50,000 p.a.',
    sector: 'Finance',
    link: 'https://www.goldmansachs.com/careers/students/programs/index.html',
    notes: 'Applied via online portal. Waiting for response.',
    created_at: '2026-05-01T10:00:00Z',
  },
  {
    id: 'app-2',
    company: 'McKinsey & Company',
    role: 'Business Analyst Intern',
    status: 'Interview',
    deadline: '2026-06-15',
    location: 'London',
    salary: '£45,000 p.a.',
    sector: 'Consulting',
    link: 'https://www.mckinsey.com/careers/students',
    notes: 'First round interview scheduled for 28 May. Prep case frameworks.',
    created_at: '2026-05-03T10:00:00Z',
  },
  {
    id: 'app-3',
    company: 'Google',
    role: 'Software Engineering Intern',
    status: 'OA/Test',
    deadline: '2026-05-28',
    location: 'London',
    salary: '£55,000 p.a.',
    sector: 'Technology',
    link: 'https://careers.google.com/students/',
    notes: '',
    created_at: '2026-05-05T10:00:00Z',
  },
  {
    id: 'app-4',
    company: 'Deloitte',
    role: 'Consulting Summer Intern',
    status: 'Applied',
    deadline: '2026-06-15',
    location: 'Manchester',
    salary: '£35,000 p.a.',
    sector: 'Consulting',
    link: 'https://www2.deloitte.com/uk/en/pages/careers/articles/student-opportunities.html',
    notes: '',
    created_at: '2026-05-07T10:00:00Z',
  },
  {
    id: 'app-5',
    company: 'HSBC',
    role: 'Global Banking & Markets Intern',
    status: 'Wishlist',
    deadline: '2026-06-01',
    location: 'London',
    salary: '£45,000 p.a.',
    sector: 'Finance',
    link: 'https://www.hsbc.com/careers/students-and-graduates',
    notes: '',
    created_at: '2026-05-08T10:00:00Z',
  },
  {
    id: 'app-6',
    company: 'Clifford Chance',
    role: 'Vacation Scheme',
    status: 'Applied',
    deadline: '2026-06-10',
    location: 'London',
    salary: '£500 / week',
    sector: 'Law',
    link: 'https://careers.cliffordchance.com/student-programmes',
    notes: '',
    created_at: '2026-05-09T10:00:00Z',
  },
  {
    id: 'app-7',
    company: 'JP Morgan',
    role: 'Technology Analyst Intern',
    status: 'Offer',
    deadline: '2026-05-25',
    location: 'London',
    salary: '£55,000 p.a.',
    sector: 'Technology',
    link: 'https://careers.jpmorgan.com/us/en/students/programs/all-programs',
    notes: 'Offer received! Need to decide by 30 May.',
    created_at: '2026-05-02T10:00:00Z',
  },
  {
    id: 'app-8',
    company: 'Boston Consulting Group',
    role: 'Associate Intern',
    status: 'Rejected',
    deadline: '2026-05-20',
    location: 'London',
    salary: '£48,000 p.a.',
    sector: 'Consulting',
    link: 'https://careers.bcg.com/students',
    notes: 'Rejected after first round.',
    created_at: '2026-05-04T10:00:00Z',
  },
  {
    id: 'app-9',
    company: 'Linklaters',
    role: 'Vacation Scheme',
    status: 'AC',
    deadline: '2026-06-05',
    location: 'London',
    salary: '£500 / week',
    sector: 'Law',
    link: 'https://careers.linklaters.com/en/students/',
    notes: 'Assessment centre on 2 June.',
    created_at: '2026-05-10T10:00:00Z',
  },
  {
    id: 'app-10',
    company: 'Microsoft',
    role: 'Software Engineering Intern',
    status: 'Interview',
    deadline: '2026-06-25',
    location: 'Reading',
    salary: '£48,000 p.a.',
    sector: 'Technology',
    link: 'https://careers.microsoft.com/students/uk/en/universityinternship',
    notes: '',
    created_at: '2026-05-11T10:00:00Z',
  },
  {
    id: 'app-11',
    company: 'Bain & Company',
    role: 'Associate Consultant Intern',
    status: 'Wishlist',
    deadline: '2026-07-01',
    location: 'London',
    salary: '£46,000 p.a.',
    sector: 'Consulting',
    link: 'https://www.bain.com/careers/find-a-role/internships/',
    notes: '',
    created_at: '2026-05-12T10:00:00Z',
  },
  {
    id: 'app-12',
    company: 'Allen & Overy',
    role: 'Spring Vacation Scheme',
    status: 'Rejected',
    deadline: '2026-05-15',
    location: 'London',
    salary: '£500 / week',
    sector: 'Law',
    link: 'https://www.allenovery.com/en-gb/global/careers/students',
    notes: '',
    created_at: '2026-05-06T10:00:00Z',
  },
]

export const MOCK_INTERNSHIPS = [
  {
    id: 'int-1',
    company: 'Goldman Sachs',
    role: 'Summer Analyst – Investment Banking',
    sector: 'Finance',
    location: 'London',
    deadline: '2026-06-30',
    salary: '£50,000 p.a.',
    link: 'https://www.goldmansachs.com/careers/students/programs/index.html',
  },
  {
    id: 'int-2',
    company: 'McKinsey & Company',
    role: 'Business Analyst Intern',
    sector: 'Consulting',
    location: 'London',
    deadline: '2026-07-15',
    salary: '£45,000 p.a.',
    link: 'https://www.mckinsey.com/careers/students',
  },
  {
    id: 'int-3',
    company: 'Google',
    role: 'Software Engineering Intern',
    sector: 'Technology',
    location: 'London',
    deadline: '2026-06-10',
    salary: '£55,000 p.a.',
    link: 'https://careers.google.com/students/',
  },
  {
    id: 'int-4',
    company: 'Deloitte',
    role: 'Consulting Summer Intern',
    sector: 'Consulting',
    location: 'Manchester',
    deadline: '2026-06-20',
    salary: '£35,000 p.a.',
    link: 'https://www2.deloitte.com/uk/en/pages/careers/articles/student-opportunities.html',
  },
  {
    id: 'int-5',
    company: 'HSBC',
    role: 'Global Banking & Markets Intern',
    sector: 'Finance',
    location: 'London',
    deadline: '2026-06-05',
    salary: '£48,000 p.a.',
    link: 'https://www.hsbc.com/careers/students-and-graduates',
  },
  {
    id: 'int-6',
    company: 'Clifford Chance',
    role: 'Vacation Scheme',
    sector: 'Law',
    location: 'London',
    deadline: '2026-06-15',
    salary: '£500 / week',
    link: 'https://careers.cliffordchance.com/student-programmes',
  },
  {
    id: 'int-7',
    company: 'Microsoft',
    role: 'Software Engineering Intern',
    sector: 'Technology',
    location: 'Reading',
    deadline: '2026-07-01',
    salary: '£48,000 p.a.',
    link: 'https://careers.microsoft.com/students/uk/en/universityinternship',
  },
  {
    id: 'int-8',
    company: 'Bain & Company',
    role: 'Associate Consultant Intern',
    sector: 'Consulting',
    location: 'London',
    deadline: '2026-07-10',
    salary: '£46,000 p.a.',
    link: 'https://www.bain.com/careers/find-a-role/internships/',
  },
  {
    id: 'int-9',
    company: 'Allen & Overy',
    role: 'Spring Vacation Scheme',
    sector: 'Law',
    location: 'London',
    deadline: '2026-06-12',
    salary: '£500 / week',
    link: 'https://www.allenovery.com/en-gb/global/careers/students',
  },
  {
    id: 'int-10',
    company: 'Unilever',
    role: 'Business & Technology Management Trainee',
    sector: 'FMCG',
    location: 'London',
    deadline: '2026-06-25',
    salary: '£32,000 p.a.',
    link: 'https://careers.unilever.com/students',
  },
  {
    id: 'int-11',
    company: 'JP Morgan',
    role: 'Technology Analyst Intern',
    sector: 'Finance',
    location: 'London',
    deadline: '2026-06-08',
    salary: '£55,000 p.a.',
    link: 'https://careers.jpmorgan.com/us/en/students/programs/all-programs',
  },
  {
    id: 'int-12',
    company: 'Linklaters',
    role: 'Vacation Scheme',
    sector: 'Law',
    location: 'London',
    deadline: '2026-06-18',
    salary: '£500 / week',
    link: 'https://careers.linklaters.com/en/students/',
  },
]
